kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quay
spec:
  host: $(SERVER_HOSTNAME)
  to:
    kind: Service
    name: quay-app
  port:
    targetPort: https
  tls:
    # TODO(alecmerdler): Experiment with switching this to "edge" if user does not provide certs...
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
