# Overlay variant for Project Quay "qui-gon" release.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  quay-version: qui-gon
bases:
  - ../../../tmp
images:
  # FIXME(alecmerdler): Testing notifications
  - name: quay.io/projectquay/quay
    newTag: clair-notifications
  - name: quay.io/projectquay/clair
    newTag: notifier-rc09
