apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    quay-component: clair-app
  name: clair-app
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: clair-app
  template:
    metadata:
      labels:
        quay-component: clair-app
    spec:
      containers:
        - image: quay.io/projectquay/clair@sha256:1f154b831e655564bb49db5ad60419e27a1a17a94a71b3dd085e376fe7bd8168
          imagePullPolicy: IfNotPresent
          name: clair-app
          env:
            - name: CLAIR_CONF
              value: /clair/config.yaml
            - name: CLAIR_MODE
              value: combo
          ports:
            - containerPort: 8080
              name: clair-http
              protocol: TCP
            - containerPort: 8089
              name: clair-intro
              protocol: TCP
          volumeMounts:
            - mountPath: /clair/
              name: config
            - mountPath: /var/run/certs
              name: certs
          readinessProbe:
            tcpSocket:
              port: 8080
          livelinessProbe:
            tcpSocket:
              port: 8080
      restartPolicy: Always
      volumes:
        - name: config
          secret:
            secretName: clair-config-secret
        - name: certs
          secret:
            secretName: quay-config-secret
            # Mount just the public certificate because we are using storage proxying.
            items:
              - key: ssl.cert
                path: quay-ssl.cert
