
apiVersion: v1
kind: Service
metadata:
  name: quay-operator-dev
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
spec:
  type: ExternalName
  externalName: 6.tcp.ngrok.io
  ports:
    - name: tcp
      protocol: TCP
      port: 9443
      targetPort: 11863
