apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-database
  labels:
    quay-component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: postgres
  template:
    metadata:
      labels:
        quay-component: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: quay-database
        - name: postgres-bootstrap
          secret:
            secretName: postgres-bootstrap
            items:
              - key: create-extensions.sql
                path: create-extensions.sql
              - key: restore.sh
                path: restore.sh
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          args: [
            "-c", "shared_buffers=256MB",
            "-c", "max_connections=2000",
          ]
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: $(POSTGRES_DEPLOYMENT_NAME)
            - name: POSTGRES_DB
              value: $(POSTGRES_DEPLOYMENT_NAME)
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-bootstrap
              mountPath: /docker-entrypoint-initdb.d
