apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-database
  labels:
    quay-component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: postgres
  template:
    metadata:
      labels:
        quay-component: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: quay-database
        - name: postgres-bootstrap
          secret:
            secretName: postgres-bootstrap
            items:
              - key: create-extensions.sh
                path: create-extensions.sh
              - key: restore.sh
                path: restore.sh
      securityContext:
        fsGroup: 0
        # FIXME(alecmerdler): This is not being marshaled from octal correctly (probably due to our YAML library) and is turing into `420`
        defaultMode: 0740
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              value: $(POSTGRES_DEPLOYMENT_NAME)
            - name: POSTGRESQL_DATABASE
              value: $(POSTGRES_DEPLOYMENT_NAME)
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_SHARED_BUFFERS
              value: 256MB
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "2000"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
            - name: postgres-bootstrap
              mountPath: /opt/app-root/src/postgresql-init
