apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: quay-operator
  source: quay-operator
  sourceNamespace: openshift-marketplace
  startingCSV: quay-operator.v2.0.0
