apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: quay-operator
spec:
  sourceType: grpc
  image: quay.io/alecmerdler/quay-operator-catalog@sha256:922f4a4a1c5cdd21e3c6cf1717cf32d379f32fd78096992b498cef558c5b408e
