# Ingress component allows external access to the Quay registry using a Kubernetes `Ingress`.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources: 
  - ./quay.ingress.yaml
# NOTE: Using `vars` in Kustomize is kinda ugly because it's basically templating, so don't abuse them
vars:
  - name: SERVER_HOSTNAME
    objref:
      kind: Service
      apiVersion: v1
      name: quay-app
    fieldref:
      fieldpath: metadata.annotations["quay-registry-hostname"]
  - name: BUILDMAN_HOSTNAME
    objref:
      kind: Service
      apiVersion: v1
      name: quay-app
    fieldref:
      fieldpath: metadata.annotations["quay-buildmanager-hostname"]
