apiVersion: v1
kind: Service
metadata:
  name: quay-app
  labels:
    quay-component: quay-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8443
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
    - name: prometheus
      protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    quay-component: quay-app
